document precompiles
PaimaStudios/paima-engine-docs pull request #52
Opened 2024-07-16 06:05 UTC by ecioppettini

documents https://github.com/PaimaStudios/paima-engine/pull/392

I'm not convinced putting this in the contract section is correct though, but in some ways it makes sense.

2024-07-18 04:03 UTC, SebastienGllmt commented on docs/home/50-smart-contracts/300-precompiles/100-introduction.md
> +    ...generatePrecompile("foo"),
We should probably give an example of what the output of `generatePrecompile` looks like since people will probably want to know what the address format looks like

2024-07-18 04:05 UTC, SebastienGllmt commented on docs/home/50-smart-contracts/300-precompiles/100-introduction.md
> +the rollup, instead of belonging to any of the underlying chains (or users).
We should probably be more explicit about the use-cases in this section (timers & events, with precompiles making it easy to query the node for these things and show them visually

2024-07-19 06:11 UTC, ecioppettini commented on docs/home/50-smart-contracts/300-precompiles/100-introduction.md
> +the rollup, instead of belonging to any of the underlying chains (or users).
Do we already have support already for anything like that though? I can add something, but it seems weird to merge that. Currently for timers the you can know the precompile from the address in the data passed to the stf, so I can comment about that, but should we include something else?

2024-07-19 15:06 UTC, SebastienGllmt approved these changes

2024-07-19 16:00 UTC, SebastienGllmt commented on docs/home/50-smart-contracts/300-precompiles/100-introduction.md
> +the rollup, instead of belonging to any of the underlying chains (or users).
Well we should try to mention at least something otherwise it's unclear what this feature is for.

On a related note, we also don't mention in the code for `createScheduledData` that the `string` parameter should come from a precompile https://github.com/PaimaStudios/paima-engine/blob/1b063c5056f60059c932d3a4227bd2c102618dc5/packages/node-sdk/paima-db/src/scheduled-constructors.ts#L26 so this should be mentioned somewhere (possible in the Paima Engine codebase itself, or by updating the `createScheduledData` documentation in the docs)

2024-07-20 02:48 UTC, SebastienGllmt requested changes
I'm going to implement this in a template and then update the docs since I think right now these docs are not really clear about how or why to use precompiles

2024-07-30 03:53 UTC, merged